.TH vit 1 "" "" "User Manuals"

.SH NAME
VIT \- Visual Interactive Taskwarrior

.SH SYNOPSIS
.B vit [-audit] <filter>

.SH DESCRIPTION
VIT (Visual Interactive Taskwarrior) is a lightweight, curses-based front end
for Taskwarrior that provides a convenient way to quickly navigate and process
tasks. VIT allows you to interact with tasks in a Vi-intuitive way.

A goal of VIT is to allow you to customize the way in which you use
Taskwarrior's core commands as well as to provide a framework for easily
dispatching external commands (both user scripts and Taskwarrior's many
external scripts). For more information on this, see vitrc(5).

.SH FILTER
The <filter> consists of zero or more search criteria that select tasks.  For
more information on this, see task(1).

.SH AUDIT
Using the -audit option is for debugging purposes and gives more information
on what's going on behind the scenes.

.SH COMMANDS

 cmd   a STRING        add a new task
 cmd   A STRING        add an annotation to the current task
 cmd   m STRING        modify the current task
 cmd   :![rw] STRING   execute "STRING" in shell. 'r' rereads, 'w' waits
 cmd   t               prepend the command prompt with ":!rw task "
 cmd   :s/OLD/NEW/     change OLD to NEW in the current task's description
 cmd   :%s/OLD/NEW/    change OLD to NEW in the current task's description
 cmd   D               denotate if over annotation, delete task if on first line
 cmd   e               edit the current task
 cmd   =               view the current task's info
 cmd   <enter>         view the current task's info
 cmd   u               undo the last change
 rpt   :REPORT         display REPORT
 rpt   :REPORT FILTER  display REPORT with FILTER
 rpt   :STRING<tab>    display REPORT using tab completion
 rpt   :<tab>          display REPORT using tab completion of all defined reports
 cmd   q               exit after confirmation
 cmd   Q               exit
 cmd   ZZ              exit
 cmd   :q              exit
 cmd   f FILTER        filter the current report with FILTER
 cmd   d               mark the current task done
 nav   j               move down one line
 nav   DownArrow       move down one line
 nav   Spacebar        move down one line
 nav   :N              move to task number N
 nav   0               move to the first line
 nav   gg              move to the first line
 nav   H               move to the first line on screen
 nav   G               move to the last line
 nav   L               move to the last line on screen
 nav   M               move to the middle line on screen
 nav   k               move up one line
 nav   UpArrow         move up one line
 cmd   N               move to the previous match when searching
 cmd   n               move to the next match when searching
 nav   ^l              refresh (redraw) the display
 nav   ^f              scroll down (forward) one page
 nav   PgDn            scroll down (forward) one page
 nav   ^b              scroll up (back) one page
 nav   PgUp            scroll up (back) up one page
 cmd   /STRING         search forwards for regular expression STRING
 cmd   ?STRING         search backwards for regular expression STRING
 cmd   P [hmln]        set the current task's priority to H, M, L, or none
 cmd   p STRING        set the current task's project to STRING
 cmd   p STRING<tab>   set the current task's project to STRING using tab completion
 cmd   p <tab>         set the current task's project using tab completion
 help  :h              view the whole help file
 help  :h cmd          view help about commands
 help  :h help         view help about help
 help  :h nav          view help about navigation
 help  :h rpt          view help about reports
 help  :h PATTERN      view help file lines matching PATTERN

.SH FILES

.TP
~/.vitrc
User configuration file.

.SH "CREDITS & COPYRIGHTS"
.PP
Copyright (C) 2012 - 2013, Steve Rader
.br
Copyright (C) 2013 - 2015, Scott Kostyshak


VIT is distributed under GNU General Public License version 3 or (at your
option) any later version. See
http://www.gnu.org/licenses/ for more information.

.SH SEE ALSO
.BR vitrc(5),
.BR task(1)

.TP
The official site is
<http://tasktools.org/projects/vit.html>

.TP
The official code repository is
<https://git.tasktools.org/EX/vit.git>

.TP
You can contact the project by emailing
<support@taskwarrior.org>

.TP
For a different but related program, see
https://github.com/blindFS/vim-taskwarrior

.SH REPORTING BUGS
.TP
Bugs in VIT may be reported to the issue-tracker at
<http://taskwarrior.org>

