#!/usr/bin/env python

import option_parser
from application import Application

def main():
    options, filters = option_parser.parse()
    Application(filters)

if __name__ == '__main__':
    main()
