#!/usr/bin/env python

import option_parser
from application import Application

def main():
  options, remainder = option_parser.parse()
  report = remainder[1] if len(remainder) > 1 else None

  Application(report)

if __name__ == '__main__':
  main()
